import type { Role } from "./types"

export interface Champion {
  name: string
  internal: string
}

function c(name: string, internal?: string): Champion {
  return { name, internal: internal ?? name }
}

export const CHAMPION_POOLS: Record<Role, Champion[]> = {
  top: [
    c("Aatrox"),
    c("Akali"),
    c("Ambessa"),
    c("Aurora"),
    c("Camille"),
    c("Cho'Gath", "Chogath"),
    c("Darius"),
    c("Dr. Mundo", "DrMundo"),
    c("Fiora"),
    c("Gangplank"),
    c("Garen"),
    c("Gnar"),
    c("Gragas"),
    c("Gwen"),
    c("Illaoi"),
    c("Irelia"),
    c("Jax"),
    c("Jayce"),
    c("K'Sante", "KSante"),
    c("Kayle"),
    c("Kennen"),
    c("Kled"),
    c("Malphite"),
    c("Mordekaiser"),
    c("Nasus"),
    c("Olaf"),
    c("Ornn"),
    c("Pantheon"),
    c("Poppy"),
    c("Quinn"),
    c("Renekton"),
    c("Rengar"),
    c("Riven"),
    c("Rumble"),
    c("Sett"),
    c("Shen"),
    c("Singed"),
    c("Sion"),
    c("Tahm Kench", "TahmKench"),
    c("Teemo"),
    c("Trundle"),
    c("Tryndamere"),
    c("Urgot"),
    c("Vayne"),
    c("Vladimir"),
    c("Volibear"),
    c("Warwick"),
    c("Wukong", "MonkeyKing"),
    c("Yasuo"),
    c("Yone"),
    c("Yorick"),
    c("Zac"),
  ],
  jungle: [
    c("Amumu"),
    c("Bel'Veth", "Belveth"),
    c("Briar"),
    c("Diana"),
    c("Dr. Mundo", "DrMundo"),
    c("Ekko"),
    c("Elise"),
    c("Evelynn"),
    c("Fiddlesticks"),
    c("Gragas"),
    c("Graves"),
    c("Hecarim"),
    c("Ivern"),
    c("Jarvan IV", "JarvanIV"),
    c("Jax"),
    c("Karthus"),
    c("Kayn"),
    c("Kha'Zix", "Khazix"),
    c("Kindred"),
    c("Lee Sin", "LeeSin"),
    c("Lillia"),
    c("Maokai"),
    c("Master Yi", "MasterYi"),
    c("Naafiri"),
    c("Nidalee"),
    c("Nocturne"),
    c("Nunu & Willump", "Nunu"),
    c("Olaf"),
    c("Poppy"),
    c("Rammus"),
    c("Rek'Sai", "RekSai"),
    c("Rengar"),
    c("Sejuani"),
    c("Sett"),
    c("Shaco"),
    c("Shyvana"),
    c("Skarner"),
    c("Taliyah"),
    c("Talon"),
    c("Trundle"),
    c("Udyr"),
    c("Vi"),
    c("Viego"),
    c("Volibear"),
    c("Warwick"),
    c("Wukong", "MonkeyKing"),
    c("Xin Zhao", "XinZhao"),
    c("Zac"),
  ],
  mid: [
    c("Ahri"),
    c("Akali"),
    c("Akshan"),
    c("Anivia"),
    c("Annie"),
    c("Aurelion Sol", "AurelionSol"),
    c("Aurora"),
    c("Azir"),
    c("Brand"),
    c("Cassiopeia"),
    c("Corki"),
    c("Diana"),
    c("Ekko"),
    c("Fizz"),
    c("Galio"),
    c("Gangplank"),
    c("Heimerdinger"),
    c("Hwei"),
    c("Irelia"),
    c("Jayce"),
    c("Karma"),
    c("Karthus"),
    c("Kassadin"),
    c("Katarina"),
    c("LeBlanc", "Leblanc"),
    c("Lissandra"),
    c("Lucian"),
    c("Lux"),
    c("Malzahar"),
    c("Naafiri"),
    c("Neeko"),
    c("Orianna"),
    c("Pantheon"),
    c("Qiyana"),
    c("Rumble"),
    c("Ryze"),
    c("Swain"),
    c("Sylas"),
    c("Syndra"),
    c("Taliyah"),
    c("Talon"),
    c("Tristana"),
    c("Twisted Fate", "TwistedFate"),
    c("Veigar"),
    c("Vex"),
    c("Viktor"),
    c("Vladimir"),
    c("Xerath"),
    c("Yasuo"),
    c("Yone"),
    c("Zed"),
    c("Ziggs"),
    c("Zilean"),
    c("Zoe"),
  ],
  adc: [
    c("Aphelios"),
    c("Ashe"),
    c("Caitlyn"),
    c("Corki"),
    c("Draven"),
    c("Ezreal"),
    c("Heimerdinger"),
    c("Jhin"),
    c("Jinx"),
    c("Kai'Sa", "Kaisa"),
    c("Kalista"),
    c("Kog'Maw", "KogMaw"),
    c("Lucian"),
    c("Miss Fortune", "MissFortune"),
    c("Nilah"),
    c("Samira"),
    c("Senna"),
    c("Seraphine"),
    c("Sivir"),
    c("Smolder"),
    c("Swain"),
    c("Tristana"),
    c("Twitch"),
    c("Varus"),
    c("Vayne"),
    c("Veigar"),
    c("Xayah"),
    c("Yasuo"),
    c("Zeri"),
    c("Ziggs"),
  ],
  support: [
    c("Alistar"),
    c("Ashe"),
    c("Bard"),
    c("Blitzcrank"),
    c("Brand"),
    c("Braum"),
    c("Fiddlesticks"),
    c("Galio"),
    c("Heimerdinger"),
    c("Hwei"),
    c("Janna"),
    c("Karma"),
    c("Leona"),
    c("Lulu"),
    c("Lux"),
    c("Maokai"),
    c("Milio"),
    c("Morgana"),
    c("Nami"),
    c("Nautilus"),
    c("Neeko"),
    c("Pantheon"),
    c("Poppy"),
    c("Pyke"),
    c("Rakan"),
    c("Rell"),
    c("Renata Glasc", "Renata"),
    c("Senna"),
    c("Seraphine"),
    c("Sett"),
    c("Shaco"),
    c("Sona"),
    c("Soraka"),
    c("Swain"),
    c("Tahm Kench", "TahmKench"),
    c("Taric"),
    c("Thresh"),
    c("Vel'Koz", "Velkoz"),
    c("Xerath"),
    c("Yuumi"),
    c("Zilean"),
    c("Zyra"),
  ],
}

const DDRAGON_VERSION = "14.24.1"

export function getChampionImageUrl(internalName: string): string {
  return `https://ddragon.leagueoflegends.com/cdn/${DDRAGON_VERSION}/img/champion/${internalName}.png`
}

export function findChampion(name: string): Champion | undefined {
  for (const pool of Object.values(CHAMPION_POOLS)) {
    const found = pool.find((ch) => ch.name === name || ch.internal === name)
    if (found) return found
  }
  return undefined
}

export const ALL_ROLES: Role[] = ["top", "jungle", "mid", "adc", "support"]

export const ROLE_LABELS: Record<Role, string> = {
  top: "Top",
  jungle: "Jungle",
  mid: "Mid",
  adc: "ADC",
  support: "Support",
}
